# .goreleaser.yml
# Build customization
builds:
  - main: ./main.go
    binary: helm-cos
    ldflags: -s -w -X github.com/imroc/helm-cos/cmd/helm-cos/cmd.version={{.Version}} -X github.com/imroc/helm-cos/cmd/helm-cos/cmd.commit={{.Commit}} -X github.com/imroc/helm-cos/cmd/helm-cos/cmd.date={{.Date}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archive:
  format: tar.gz
  replacements:
    amd64: x86_64
    darwin: Darwin
    linux: Linux
